version: '3.9'

services:
  postgres:
    image: postgres:14
    container_name: postgres_sm_room
    env_file:
      - .env
    environment:
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_NAME}'
    ports:
      - "5433:5432"
    volumes:
      - db_data_sm:/var/lib/postgresql/data
volumes:
  db_data_sm: